version: '3.8'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: A06£6cG@tp.*
      MYSQL_DATABASE: sistema_monitoramento_fabril
      MYSQL_USER: joao
      MYSQL_PASSWORD: joao123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  db_data:
  grafana_data: